name: UML Workflow
run-name: ${{ github.actor }} UML

on: [push]

# SCHEDULE WITH CRON
# Check: https://jasonet.co/posts/scheduled-actions/
# Check: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
# Check: https://github.com/actions/setup-python/blob/main/.github/workflows/test-python.yml

env:
  INIT_FILE: src/__init__.py
  
jobs:
  UML:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip" # caching pip dependencies
      - run: sudo apt-get install -y graphviz
      - run: pip install pylint
      - run: echo "Pyling installed"
      - run: echo "salut" >> src/__init__.py
      - run: echo "Building the UML graphs"
      - run: pyreverse -o png src/ --output-directory uml/ -Ab
      - run: rm $INIT_FILE
      - name: Commit files # commit the output folder
        run: |
          git config --local user.email "lucasrodriguez.08@outlook.com"
          git config --local user.name "GitHub Action Hello"
          git add ./uml
          git commit -m "UML workflow update: $(date)"
      - name: Push changes # push the output folder to your repo
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.KEY }}
          force: true
