name: UML Workflow
run-name: UML Workflow

on:
  push:
    branches:
      - "main"
    paths:
      - "src/*.py"

# SCHEDULE WITH CRON
# Check: https://jasonet.co/posts/scheduled-actions/
# Check: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
# Check: https://github.com/actions/setup-python/blob/main/.github/workflows/test-python.yml

env:
  INIT_FILE: src/__init__.py

jobs:
  UML:
    runs-on: ubuntu-latest
    steps:
      # Checking repository content
      - name: Check out repository code
        uses: actions/checkout@v3

      # Checking any file changes
      - name: Get changed files in the docs folder
        id: changed-files-specific
        uses: tj-actions/changed-files@v35
        with:
          files: src/*.py

      # Installing Python 3.10
      - name: Installing Python
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip" # Caching pip dependencies

      # Installing Graphviz + PyLint
      - name: Installing Python + dependencies
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          sudo apt-get install -y graphviz
          pip install pylint

      # Creating UML diagrams
      - name: Creating UML diagrams
        run: |
          echo "Creating temporary file"
          echo "Hello world" >> src/__init__.py
          echo "Creating UML diagrams"
          pyreverse -o png src/ --output-directory uml/ -Ab
          echo "Removing temporary file"
          rm $INIT_FILE          
          
      # Commiting the file changes
      - name: Commiting the changes
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          git config --local user.email "lucasrodriguez.08@outlook.com"
          git config --local user.name "GitHub Action Hello"
          git add ./uml
          git commit --allow-empty -m "UML workflow update: $(date)"

      # Pushing to the main branch
      - name: Pushing to the main branch
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.KEY }}
          force: true
