name: UML Workflow
run-name: ${{ github.actor }} UML

on: [push]

# SCHEDULE WITH CRON
# Check: https://jasonet.co/posts/scheduled-actions/
# Check: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
# Check: https://github.com/actions/setup-python/blob/main/.github/workflows/test-python.yml

env:
  INIT_FILE: src/__init__.py
  
jobs:
  UML:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        
      # Checking if we have to run PyReverse
      - name: Get changed files in the docs folder
        id: changed-files-specific
        uses: tj-actions/changed-files@v35
        with:
          files: src/*.py  # Alternatively using: `docs/**` or `docs`

      - name: Run step if any file(s) in the docs folder change
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          echo "One or more files in the docs folder has changed."
          echo "List all the files that have changed: ${{ steps.changed-files-specific.outputs.all_changed_files }}"
      - name: Installing Python
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        uses: actions/setup-python@v4
        with:
           python-version: "3.10"
           cache: "pip" # caching pip dependencies
      - name: Installing Python + dependencies
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          sudo apt-get install -y graphviz
          pip install pylint
          echo "Pyling installed"
          echo "salut" >> src/__init__.py
          echo "Building the UML graphs"
          pyreverse -o png src/ --output-directory uml/ -Ab
          rm $INIT_FILE
          git config --local user.email "lucasrodriguez.08@outlook.com"
          git config --local user.name "GitHub Action Hello"
          git add ./uml
          git commit -m "UML workflow update: $(date)"
      - name: Pushing
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.KEY }}
          force: true
